services:
  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    stop_grace_period: 1s
    volumes:
      - ~/ts:/opt/ts
    restart: unless-stopped
  transcoding-proxy:
    build: .
    stop_grace_period: 1s
    volumes:
      - ./transcoded/:/cached/
      - ./proxy-cached/:/proxy-cached/
      - ./src/:/app/src/
      - ./tmp/:/tmp/
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - PROXY_TARGET=http://torrserver:8090
      - CACHE_PATH=/cached/
      - PORT=3001
    ports:
      - "8090:80"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
    #   interval: 3s
    #   timeout: 10s
    #   retries: 15
  # test:
  #   image: curlimages/curl:8.10.1
  #   stop_grace_period: 1s
  #   depends_on:
  #     transcoding-proxy:
  #       condition: service_healthy
  #   command:
  #     curl --progress-bar "http://transcoding-proxy:3001/stream/Sintel.mp4?link=08ada5a7a6183aae1e09d831df6748d566095a10&index=6&play&quality=0" -o /dev/null
