services:
  origin-proxy:
    image: ghcr.io/online-video-platform/origin:main
    restart: unless-stopped
    stop_grace_period: 1s
    volumes:
      - ./cached/:/cached/
    environment:
      - TARGET=http://nginx:80
      - CACHE_PATH=/cached/
      - PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 3s
      timeout: 10s
      retries: 15
  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    stop_grace_period: 1s
    volumes:
      - ~/ts:/opt/ts
    restart: unless-stopped
  nginx:
    image: nginx:latest
    stop_grace_period: 1s
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tmp/:/tmp/cache/:rw
    restart: unless-stopped
  transcoding-proxy:
    build: .
    stop_grace_period: 1s
    depends_on:
      origin-proxy:
        condition: service_healthy
    volumes:
      - ./cached/:/cached/
      - ./src/:/app/src/
    environment:
      - PROXY_TARGET=http://origin-proxy:3001
      - CACHE_PATH=/cached/
      - PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 3s
      timeout: 10s
      retries: 15
  test:
    image: curlimages/curl:8.10.1
    stop_grace_period: 1s
    depends_on:
      transcoding-proxy:
        condition: service_healthy
    command:
      curl --progress-bar "http://transcoding-proxy:3001/stream/Sintel.mp4?link=08ada5a7a6183aae1e09d831df6748d566095a10&index=6&play" -o /dev/null
