# docker run -d -p 3001:3001 --name transcoder -e TARGET=http://nginx:80 -e CACHE_PATH=/cached -e PORT=3001 ghcr.io/online-video-platform/origin:main
services:
  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    stop_grace_period: 1s
    volumes:
      - ~/ts:/opt/ts
    restart: unless-stopped
  origin-proxy:
    image: ghcr.io/online-video-platform/origin:main
    stop_grace_period: 1s
    volumes:
      - ./origin-cached/:/cached/
      - ./tmp/:/tmp/
    environment:
      - TARGET=http://torrserver:8090
      - CACHE_PATH=/cached/
      - PORT=3001
    depends_on:
      torrserver:
        condition: service_started
  transcoding-proxy:
    image: ghcr.io/online-video-platform/transcode:main
    stop_grace_period: 1s
    volumes:
      - ./transcoded/:/cached/
      - ./proxy-cached/:/proxy-cached/
      - ./tmp/:/tmp/
    environment:
      - PROXY_TARGET=http://origin-proxy:3001
      - CACHE_PATH=/cached/
      - PORT=3001
    ports:
      - "8090:3001"
    depends_on:
      origin-proxy:
        condition: service_started
